name: Node.js Build with docker to aci

on:
  workflow_dispatch:
  push:

env:
  artifact-name: my-app
  resource-group: xxxxxxx-rg
  acr-registry: xxxxxxx
  image-name: counterfunction
  tag: latest
  dockerfile: Dockerfile

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v3
    - uses: ./.github/actions/build-node
      with:
        artifactName: ${{env.artifact-name}}

  build-docker:
    runs-on: ubuntu-latest
    needs: build
    outputs:
      image-name: ${{ steps.acr-build.outputs.image-ref }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name:  ${{ env.artifact-name }}
        path: dist
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: ACR Build
      id: acr-build
      uses: azure/CLI@v1
      with:
        inlineScript: |
          echo "image-tag=${{ env.tag }}" >> $GITHUB_OUTPUT
          echo "Using tags ${{ env.tag }}"
          echo "image-ref=${{ env.acr-registry }}.azurecr.io/${{ env.image-name }}:${{ env.tag }}" >> $GITHUB_OUTPUT
          az acr build -r ${{ env.acr-registry }} -f ${{ env.dockerfile }} -t "${{ env.image-name }}:${{ env.tag }}" ./

  deploy-container-instance:
    runs-on: ubuntu-latest
    needs: build-docker
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: ACI Build and Push
      id: aci
      uses: azure/CLI@v1
      with:
        inlineScript: |
          cd infra
          guidLowerDashed=$(cat /proc/sys/kernel/random/uuid)
          guidLower=${guidLowerDashed//"-"/""}
          deploy_name="${GITHUB_REPOSITORY#*/}_$guidLower"
          az deployment group create --name $deploy_name --resource-group ${{ env.resource-group }} --template-file main.bicep --parameters image=${{ needs.build-docker.outputs.image-name }} acrName=${{ env.acr-registry }}
    
