name: comment made

on:
  issue_comment:
    type:
      - created
env:
  TRIGGER_WORD: "//issuebot"

permissions:
  issues: write

jobs:
  event-recieved:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2
      - name: Check if trigger word is mentioned
        uses: actions/github-script@v6
        id: get-request
        with:
          script: |
            const targetString = context.payload.comment.body;
            const wordToFind = process.env.TRIGGER_WORD;
  
            if (targetString.includes(wordToFind)) {
              console.log(`The word "${wordToFind}" was found in the string "${targetString}".`);
              const parsedRequest = targetString.replace(wordToFind,"");
              return { 
                result: true,
                request: parsedRequest
              };
            } else {
              console.log(`The word "${wordToFind}" was not found in the string "${targetString}".`);
              return { 
                result: false
              };
            }
      - name: display result
        uses: actions/github-script@v6
        if: ${{ fromJSON(steps.get-request.outputs.result).result == true }}
        with:
          script: |
            console.log("request is: ${{ fromJSON(steps.get-request.outputs.result).request }}");
