name: Matrix - NGINX Service Example
# here I am using 2 services and using matrix so I dont repeat the initial code which was

        # - name: Wait for Web1 to be ready
        # run: |
        #   until curl -f http://localhost:8080; do
        #     echo "Waiting for Web1 to be ready..."
        #     sleep 5
        #   done

        # - name: Wait for Web2 to be ready
        # run: |
        #   until curl -f http://localhost:8081; do
        #     echo "Waiting for Web2 to be ready..."
        #     sleep 5
        #   done

on:
  workflow_dispatch:

jobs:
  test_nginx:
    name: Check NGINX Service
    runs-on: ubuntu-latest
    services:
      Web1:
        image: nginx:latest
        ports:
          - 8080:80
        options: >-
          --health-cmd "curl -f http://localhost || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
      Web2:
        image: nginx:latest
        ports:
          - 8081:80
        options: >-
          --health-cmd "curl -f http://localhost || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5       
    strategy:
      matrix:
        service:
          - name: Web1
            port: 8080
          - name: Web2
            port: 8081

    steps:
      # - name: Check out repository code
      #   uses: actions/checkout@v3

      - name: Wait for ${{ matrix.service.name }} to be ready
        run: |
          until curl -f http://localhost:${{ matrix.service.port }}; do
            echo "Waiting for ${{ matrix.service.name }} to be ready..."
            sleep 5
          done

      - name: Verify ${{ matrix.service.name }} is running
        run: |
          echo "${{ matrix.service.name }}"
          curl -I http://localhost:${{ matrix.service.port }}